return {
  TILE_HEIGHT = 16,
  TILE_WIDTH = 16,
  LOVE_CALLBACKS = {
    'draw',
    -- 'errorhandler', We cannot obtain default errorhandler
    'load',
    'lowmemory',
    'quit',
    'run',
    'threaderror',
    'update',
    'directorydropped',
    'displayrotated',
    'filedropped',
    'focus',
    'mousefocus',
    'resize',
    'visible',
    'keypressed',
    'keyreleased',
    'textedited',
    'textinput',
    'mousemoved',
    'mousepressed',
    'mousereleased',
    'wheelmoved',
    'gamepadaxis',
    'gamepadpressed',
    'gamepadreleased',
    'joystickadded',
    'joystickaxis',
    'joystickhat',
    'joystickpressed',
    'joystickreleased',
    'joystickremoved',
    'touchmoved',
    'touchpressed',
    'touchreleased',
  },
}